# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmniw1 <- function(A, V, S, nu) {
    .Call(`_bvarPANELs_rmniw1`, A, V, S, nu)
}

sample_m <- function(aux_A, aux_V, aux_s, aux_w, prior) {
    .Call(`_bvarPANELs_sample_m`, aux_A, aux_V, aux_s, aux_w, prior)
}

sample_w <- function(aux_V, prior) {
    .Call(`_bvarPANELs_sample_w`, aux_V, prior)
}

sample_s <- function(aux_A, aux_V, aux_Sigma, aux_m, prior) {
    .Call(`_bvarPANELs_sample_s`, aux_A, aux_V, aux_Sigma, aux_m, prior)
}

