# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bvarPANEL <- function(S, Y, X, prior, starting_values, thin, show_progress, rate_target_start_initial) {
    .Call(`_bvarPANELs_bvarPANEL`, S, Y, X, prior, starting_values, thin, show_progress, rate_target_start_initial)
}

rmniw1 <- function(A, V, S, nu) {
    .Call(`_bvarPANELs_rmniw1`, A, V, S, nu)
}

sample_m <- function(aux_A, aux_V, aux_s, aux_w, prior) {
    .Call(`_bvarPANELs_sample_m`, aux_A, aux_V, aux_s, aux_w, prior)
}

sample_w <- function(aux_V, prior) {
    .Call(`_bvarPANELs_sample_w`, aux_V, prior)
}

sample_s <- function(aux_A, aux_V, aux_Sigma, aux_m, prior) {
    .Call(`_bvarPANELs_sample_s`, aux_A, aux_V, aux_Sigma, aux_m, prior)
}

log_kernel_nu <- function(aux_nu, aux_Sigma_c_cpp, aux_Sigma_c_inv, aux_Sigma, prior_lambda, C, N, K) {
    .Call(`_bvarPANELs_log_kernel_nu`, aux_nu, aux_Sigma_c_cpp, aux_Sigma_c_inv, aux_Sigma, prior_lambda, C, N, K)
}

mcmc_accpetance_rate1 <- function(mcmc) {
    .Call(`_bvarPANELs_mcmc_accpetance_rate1`, mcmc)
}

sample_nu <- function(aux_nu, posterior_nu, aux_Sigma_c_cpp, aux_Sigma_c_inv, aux_Sigma, prior, iteration, scale, rate_target_start_initial) {
    .Call(`_bvarPANELs_sample_nu`, aux_nu, posterior_nu, aux_Sigma_c_cpp, aux_Sigma_c_inv, aux_Sigma, prior, iteration, scale, rate_target_start_initial)
}

sample_Sigma <- function(aux_Sigma_c_inv, aux_s, aux_nu, prior) {
    .Call(`_bvarPANELs_sample_Sigma`, aux_Sigma_c_inv, aux_s, aux_nu, prior)
}

sample_AV <- function(aux_A_c_cpp, aux_Sigma_c_inv, aux_s, aux_m, aux_w, prior) {
    .Call(`_bvarPANELs_sample_AV`, aux_A_c_cpp, aux_Sigma_c_inv, aux_s, aux_m, aux_w, prior)
}

sample_A_c_Sigma_c <- function(Y_c, X_c, aux_A, aux_V, aux_Sigma, aux_nu) {
    .Call(`_bvarPANELs_sample_A_c_Sigma_c`, Y_c, X_c, aux_A, aux_V, aux_Sigma, aux_nu)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_bvarPANELs_RcppExport_registerCCallable`)
})
